### ISSUE TITLE
ベンダー名を考える

### ISSUE THREAD

**Issue by sota1235** [owl/url-thumbnail#2]
Packagistに`owl/url-thumbnail`で登録しようとしてたら`owl`が取られてたので別のやつが必要。
むーん

**Comment by fortkle** [comment]
`owl-library` とかでいいんじゃないかな。本体はpackagistに登録しないだろうし。
長いのが気になるなら `owl-lib`とか。

**Comment by sota1235** [comment]
なるほど。それで！

**Comment by sota1235** [comment]
done!!!
https://packagist.org/packages/owl-lib/url-thumbnail
